### ISSUE TITLE
Reality Shock: Video "Dirty Laundry" (formerly "Data Breach")

### ISSUE THREAD

**Issue by ghost** [humanetech-community/awareness-program#10]
# "Dirty Laundry" Deliverable

## Info 

- Name: **Dirty Laundry**
- Type: **Video**
- Campaign: [Reality Shock](campaigns/reality-shock/README.md)
- General discussion: [Forum topic title here](forum-topic-url)

## Summary 

Short video showing someone experiencing the violent aftermath of a severe data breach.

## Goals

- Exposing the grave dangers of entrusting tech companies with very sensitive and private information (here, the person's web search history).

- Highlighting that we have to come to blindly trust technology with our most intimate secrets.

- Get the audience to ponder whether they should immediately stop giving their private information away.

## Concept

A typical user of a web search engine (let us call it "Search") has grown accustomed to search about the most private and potentially embarrassing topics. He wakes up to realize a massive data breach has leaked many users' search history to all their connections. We follow him going through the aftermath, leading to his ultimate suicide. If was a false awakening. He finally - this time, really - wakes up and realizes this has all been just a nightmare. He then immediately checks and gets to realize that no one can be sure your search history can be deleted an Search's servers.

## Strategy

- This deliverable does not require additional strategy. Please refer to [campaign strategy](campaigns/reality-shock/README.md#strategy).

## Script

The video starts with the main character (let us say a man, in his forties, married with two kids) at night at home in bed playing with his laptop (wife is next to him, asleep). We see him using a search engine called Search, which he uses to search about increasingly private and potentially embarrassing topics, starting with benign topics such as career tips, etc and progressing through a natural succession to more and more compromising topics. In the process, we come to understand he is facing a mid life crisis, and seems to fantasize about a junior co-worker. While searching, we seem him hesitate for a second, but he proceeds anyway. 

These are the search queries he would enter on Search (in brackets what Google gives us for these):

- "Career promotion tips" (innocent links on how to advance your career)
- "Boss is a prick" (links on how to deal with a difficult boss)
- "Attractive colleague" (includes links to people's experience with this issue)
- "Hot colleague" (first link is "How to attract and seduce your hot colleague")
- "Business trip affair" (4th link is "How to cheat on your wife on a business trip")
- "Fake business trip" (Same idea but emphasizes he is thinking of planning one)
- "Hot office videos" (No need to describe what you get there)

He clears search history, switches off his laptop and bed light and falls asleep.

He wakes up around 6am to a call from a good friend, one of his male colleagues, who tells him "man, something very bad happened last night. We're in deep shit. You'd better check your emails asap". He goes to her emails and realizes the inbox is full with all sorts of messages with subject lines including insults, LOL, and ONE message from the friend linking to a news article. He clicks on the link and sees that the whole front page of the newspaper is dedicated to the most severe data breach in history, involving Search. He reads on to see that the breach resulted in sharing the search history of millions of users to all their connections, including colleagues, bosses, wives, friends, etc, etc.

It is now 7am and he leaves for the office (wife still asleep). On the street, he sees many people running in the opposite direction while talking on the phone. At the office, his boss is waiting for him at his corner office to announce he is fired with immediate effect. He goes to a coffee place, only to realize his credit card is rejected.

Next scene he is seen fighting with his wife on the phone, she tells him it is over. Next scene, he goes to see his father for advice, his father refuses to look him in the eye and just shows him the door. Next scene, he sits with some of his friends in a bar. They have all been affected by the hack. They sit there, with their drinks, not saying a word, looking at each other. He ends walking in a park, where it seems strangers are looking at him suspiciously. He is seen back home (wife and kids have left), where after a few seconds collecting his thoughts, he opens a drawer, revealing a gun. He glanced at his laptop screen on the table and focuses on Search's main page, which shows the slogan "Everything you need is at your fingertips".

At that moment we hear a loud bang and the screen goes black and the music stops. But it was all a nightmare. He wakes up in sweat. It is the middle of the night. He calms down for a few seconds, then grabs his laptop. We see him type: "permanently delete personal data on Search?". The results page shows many links that all seem to imply it is impossible to be 100% sure. One of the links maybe humanetech.com (to be discussed).

## Duration

- Short, but duration still to be determined.

## Music

Three Little Birds (Bob Marley) provided we can get copyrights. Listen [here on Youtube](https://www.youtube.com/watch?v=LanCLS_hIo4)

## Production

- Production requirements and details are still to be determined.

## Funding

- Funding requirements have yet to be determined. 

## Team

- To be determined

## Resources

- Preferable music to use by Bob Marley, "Three Little Birds": [Listen here on Youtube](https://www.youtube.com/watch?v=LanCLS_hIo4)

**Comment by micheleminno** [comment]
I was wondering if it's not too much for a search history made public. After all she found information about her connections that were public. Why should they be so upset with her?

**Comment by georgeshk** [comment]
It is a nightmare scenario indeed. Why is it so scary is that many of us search for topics on very intimate private issues (say sex for example).

I think my scenario was not clear enough. She is not searching for her friends' online details, but say for topics like "why is my best friend such a c***?" or "I think my boyfriend is cheating on me".

So we would need to brainstorm about some search topics that would make many of her friends upset, or make her friends or family find her despicable. I will think about it.

**Comment by micheleminno** [comment]
Perhaps she reveals by the searches she made something private about herself. Something like “how to cure depression” or other medical issues, or sexual orientation, .. do that her boss wants to fire her with some excuse..

**Comment by georgeshk** [comment]
Yeah something like that. It needs to be progressive. She starts with something rather innocent, such as "tips to look more attractive", then proceeds to "boyfriend neglects me", "my best friend is a c***", "is my boyfriend cheating on me", to "unsastified in bed", "spice up sex life", "threesomes", etc. You get the drift

**Comment by aschrijver** [comment]
> I was wondering if it's not too much for a search history made public. After all she found information about her connections that were public. Why should they be so upset with her?

I can see what @micheleminno means, but I also get your, @georgeshk, intention to focus on the search results.

The concept of a 'Data Breach' is very actual these days, and continuously in the news. It is also much broader, and usually does not pertain to 'search results', but a platform that is hacked and all your accounts and/or complete personal information now on the Dark Web, etc. 

But search results is a good topic no matter what. Most people do not realize they give away their psyche to e.g. Google.

But I think there should more video's related to data breaches. Maybe the working name of this video should be changed to something that indicates the scope better, like Search Lost, or similar.

A nice example - though dystopic sci-fi, not anywhere near the present day - of full breach is the [Hyper Reality](http://hyper-reality.co/) video.

**Comment by aschrijver** [comment]
Yes, could be. Some more brainstorming: Searched Too Much, Found Out, Unintended Search Results. You pick the one you like most, is most fitting :)

**Comment by aschrijver** [comment]
That is true, but it does not make reference to search, and als 'dirty laundry' is a broad concept too, more criminal, or illegal connotation.

**Comment by georgeshk** [comment]
No la, dirty laundry refers to something that should be kept private, but in this case, is not. We all have dirty laundry in the common use of the expression, there is nothing illegal or criminal there!

**Comment by georgeshk** [comment]
According to Merriam Webster:

Definition of dirty laundry. : private matters whose public exposure brings distress and embarrassment

**Comment by aschrijver** [comment]
Let's go with that then :)

**Comment by georgeshk** [comment]
@micheleminno 

> I was wondering if it's not too much for a search history made public. After all she found information about her connections that were public. Why should they be so upset with her?

Corrected the script to make it clear she is not searching for info about her connections, but for embarrassing topics that may relate to her connections (e.g. sex life/boyfriend, friendship/best friend, etc..)

**Comment by georgeshk** [comment]
Here is an attempt at the queries she would run on Search, progressing in level of intimacy and potential embarrassment. One issue: there needs to be continuity in the topics she searches, making it natural to move from one to the next. So we cannot address all subjects that are relevant to each of her job, boyfriend, girlfriends and parents. We need to find a theme that will embarrass her with everyone, but also cause her boss to fire her (e.g. if we were to pursue a kinky theme (very common topic), we could have "Should I date my boss?")

I suppose we could actually use Google to produce the actual results of each queries (it helped me find continuity of topics that are searched), and then reformat to fit the fictitious "Search" platform. I added in brackets a very rough description of what Google actually produced. No need in the video to show all search results, only to provide the basis for continuity whenever it is not obvious (see the "small penises" query, following the "happy sex life" query).

Here it is (in that order):

- "tips on relationships" (pretty innocent links to dating tips and healthy relationships)
- "happy sex life" (top links rather innocent, in the middle one link mentions men with small penises)
- "small penises" (top link talking about a woman's experience with a guy with a small penis)
- "10 reasons why you should break up with your boyfriend" (most links proposing lists of good reasons to break up)
- "should I date other men" (many links encouraging women to do so!)
- "should I sleep with my boss" (links about women's experiences, notes of caution, etc)
- "threesome videos" (well, I did not run that search but I can guess what would have shown up...)

I reckon this may be a bit crude (I feel kind of embarrassed actually, and I definitely hope there won't be any data breach tonight after searching all this!) and not to everyone's tastes (especially for the ladies out there), but let us keep in mind that many, many people (I don't have statistics on how much of the population does, though) run all sorts of crazy searches into very embarrassing topics. These queries do not make her especially evil, it is just an illustration of how comfortable we have become with trusting search engines and how scary that should be.

Any suggestion to improve are welcome.

**Comment by aschrijver** [comment]
> I suppose we could actually use Google to produce the actual results of each queries 

I think it is important that - while Big Tech companies have their issues regarding humane technology - we don't 'attack' or judge them directly. We don't want them to start working against us, but adopt best-practices with our (and many other's) nudges. Also we need to run social media marketing using their platforms.

So I suggest that we use actual search results, but edit the html to show different (may be visually similar) logo and with some minor style changes (font / color). Can be easily done by 'Inspect element' (right click) on a page and live editing (browser Developer Tools), before taking screenshots.

**Comment by aschrijver** [comment]
> Many people [..] run all sorts of crazy searches into very embarrassing topics

Yes, and even worse. These are some really good query examples (but, if need be we can create separate issue to refine them and make final).

**Comment by georgeshk** [comment]
> I think it is important that - while Big Tech companies have their issues regarding humane technology - we don't 'attack' or judge them directly.

Fully agreed. See my disclaimer in the issue on the "a coffee place" video. Tech companies are not an enemy, they have the power to reinvent themselves by adopting humane technology principles, while still striving.

> So I suggest that we use actual search results, but edit the html to show different (may be visually similar) logo and with some minor style changes (font / color)

That was my idea. Google's actual results give us ideas as to what search results would look like on Search. No need to copy paste, can just get inspiration to draft our own HTML page (I could do that).

**Comment by georgeshk** [comment]
> but, if need be we can create separate issue to refine them and make final

In my view, let us keep all discussions on one thread (too many threads, too few people, hard to link between all related issues)

**Comment by patmatsu** [comment]
I don't like this characterization of a female. It reinforces negative characteristics of women, showing them as weak, manipulative, susceptible to using seduction, etc. Why can't it be a teenaged boy, someone influenced by his game playing to look up bombs, weapons, etc. Perhaps after his searching over the course of a week, a government agent shows up at his parents' house?

**Comment by georgeshk** [comment]
> I don't like this characterization of a female. It reinforces negative characteristics of women

I anticipated reactions such as yours, especially from the ladies out there, and as I said, I felt embarassed. It was just an attempt at illustrating a progressive, increasingly embarassing search for related topics.

I like the idea of it to be shocking, and the kinky stuff is, I am afraid, the best example.

After reading your post, with which I fully agree, I propose to turn things around while keeping the same principles, using a male character instead (guys will be much less offended, if at all, than women).

Another point: it is a fiction, hence it does not represent all women, but anyway, thanks for your feedback, it is good to realize this now rather than later.

I will make another attempt this time using a male character.

**Comment by patmatsu** [comment]
@georgeshk, you are kind to take my thoughts into consideration. I apologize for expressing myself so strongly.

If you were following the confirmation of Justice Brett Kavanaugh, you may know that one of the phrases that came up during his second hearing was "Devil's Triangle." He prevaricated (yes, I'm deliberately using that word instead of the more common one) because he didn't want to be caught knowing something (he thought) he wasn't supposed to know. He claimed it was a drinking game, but it was a term for a kind of threesome.

The followup to that hearing was that someone in the U.S. House of Representatives tweaked Wikipedia so that BK's made-up definition appeared in its pages. That is, it appeared to be legitimate. A bot that tracks Congressional tweaks to Wikipedia caught the change, and it was later removed.

That would be a provocative detail to add to the video, but I leave that decision to you and @aschrijver. Thank you again for tolerating this dissenting opinion :-)

**Comment by georgeshk** [comment]
> I apologize for expressing myself so strongly.

Not at all. To be honest, I had concerns too, and your feedback confirmed these doubts.

Sadly, women are often stereotyped in many ways (which my first attempt did, although as I said, she was a fictitious character). I guess I thought it would have been more dramatic (more embarassing) as  it may be harder for a woman to publicly discuss such issues than a man (men regularly make lewd jokes about all sorts of kinky topics - let us not go there...). Maybe this is another stereotype, but I very seldom came across women who discuss sex topics in public. As to men, well, the subject comes up pretty much every day.

Anyway, I rely on your first, instinctive reaction. If 50% of the public is shocked (here, in a bad way), then that is not a great starting point.

I will try to use a male character instead, but please understand if I use another stereotype and explore a different avenue (sexual harassment, for instance) that would be more likely to embarrass men (if it was revealed that a guy searched about threesome videos, most likely his reaction would be, "so what?")

**Comment by patmatsu** [comment]
Your points are well made and well taken. Thank you. I look forward to whatever you come up with.

**Comment by georgeshk** [comment]
Hi @patmatsu 

I changed the general script in the very first post (at the top) of this thread/issue. I hope you like it better than the first. I am personally much more comfortable, it was great to have your views.

Soon I will make another attempt at exactly what topics exactly this middle-aged man will look for on Search.

**Comment by georgeshk** [comment]
Ok, here we go, this time I did not always add actual results from Google, as I already have an idea of continuity, instead I add a description of what the search results do look like or would look like (in brackets), leading him from one topic to the next.

- "Career promotion tips" (innocent links on how to advance your career)
- "Boss is a prick" (links on how to deal with a difficult boss)
- "Attractive colleague" (includes links to people's experience with this issue)
- "Hot colleague" (first link is "How to attract and seduce your hot colleague")
- "Business trip affair" (4th link is "How to cheat on your wife on a business trip")
- "Fake business trip" (Same idea but emphasizes he is thinking of planning one)
- "Hot office videos" (No need to describe what you get there)

Remember: after all this, he **clears his search history**. However, as we find out at the very end, it is impossible to make sure it is deleted from all servers. This is to incite the public to be cautious when searching for private topics: measures you take to cover your tracks will never be comparable to actually avoid the practice in the first place.

**Comment by patmatsu** [comment]
See attached for another possibility.

![screen shot 2018-10-12 at 2 31 44 pm](https://user-images.githubusercontent.com/43923185/46899160-a875ad00-ce2b-11e8-966a-ee3776d7dad9.png)

**Comment by georgeshk** [comment]
Thanks for sharing. Quite distinctive concept, which could make for a different story/video.

**Comment by georgeshk** [comment]
> See attached for another possibility.

I take this opportunity for a gentle reminder for all of us here: when discussing a concept or deliverable, we should try to stay on topic (otherwise, the preferred route is to create a new issue and provide all details there).

Also, in the particular example of deliverables, we should also try to help improve what is proposed, either by elaborations or improvements, without (unless it is justified, of course, as your previous remarks on women stereorypes) proposing an entirely new direction or massive changes to most aspects (which, again, should form the basis of a separate concept).

**Comment by patmatsu** [comment]
Yes, I should have explained why I was attaching that. I will delete.

**Comment by micheleminno** [comment]
Sorry bu I don’t agree with the message of this video. What’s the suggested behavior here? To wash our own dirty laundry at home? Is it the real problem a potential data breach? I think the issue is a centralized supercomputer getting accurate profiles of billion people out of their search queries, and keeping them active and each day more accurate for its own purposes. Even in a perfect world without data breaches. Otherwise the message of this video could be similar to the advice:”pay cash, no traces left”, which I fully disagree.

**Comment by georgeshk** [comment]
Hello @micheleminno

Thanks for your input. The basic objective here is to alert users on the dangers of trusting apps with your most private details. In this story, we follow someone who, after trusting a search engine, is victim of a masive data breach. The morale is 'whatever you input online, the whole world could know about it."

The actual breach at the conclusion exposes this: "dont trust anything online".

**Comment by georgeshk** [comment]
>  I think the issue is a centralized supercomputer getting accurate profiles of billion people out of their search queries.

I sympathize with this, but it is not the theme here. Here we are focusing on what happens when your private queries become public.

**Comment by georgeshk** [comment]
I took some time to think long and hard about the message after the video. I feel the reference to the Ashley Madison breach is not ideal. That would lead viewers to think the whole point of the video is to warn those who are contemplating extramarital affairs to be careful online. And it would also makes most people unconcerned. Thanks @micheleminno for provoking this rethinking.

I would thus propose the following instead.

"In March 2018, a shocking article in *The Guardian* revealed in detail the extent of the information major tech companies such as Facebook and Google keep on their users.

[Pause]

"This information, which for many users represents gigabytes of data, includes very private details including your emails, messages, pictures, documents, search history, and app usage, allowing tech companies to build highly detailed profiles that advertisers or other apps can use."

[Pause, new screen]

"Every year, increasingly sophisticated hackers gain access to highly private data we entrust with the most popular apps and websites."

[Pause]

"At any time, your life could be ruined in an instant."

[Pause]

"Protect yourself. Never do, post or enter anything online you wouldn't want the whole world to know."

**Comment by patmatsu** [comment]
>allowing tech companies to build highly detailed profiles that advertisers or other apps can use.

Do you want to add here that identities can be stolen or duplicated?

**Comment by georgeshk** [comment]
> Do you want to add here that identities can be stolen or duplicated?

Although these are valid concerns indeed, these issues are not directly related to the concept of this video.

**Comment by micheleminno** [comment]
Good rethinking, it is much better now. Still I would not put emphasis on **personal effort** to protect ourself individually because of this precious personal profile that can be hacked. I would question about the right of these companies to collect and keep those profiles. I'd ask viewers: "Do you want that someone else has a detailed profile of you, a knowledge of you even more complete and deep of that one that you have about yourself?". Then once these profile are out there in some database, they can be obviously hacked, but according to me this is not the main issue here, it's a consequence of the other problem, that is the existence of those profiles.

**Comment by georgeshk** [comment]
That is the whole point. We are entirely too comfortable giving away private details against mostly free services. It is already implied in the text that it is revolting that tech companies document our personal lives in every detail. But the point is, nobody changes their behaviors knowing that. They just keep trusting tech companies. We need to highlight how unsafe it is to trust your private life to not infallible organizations. Viewers can act on that, they cannot do much about forcing tech companies to collect data, which I agree, is a sad thing.

**Comment by micheleminno** [comment]
> Viewers can act on that, but they cannot do much about forcing tech companies to stop collecting data, which I agree, is a sad thing.

This is the point where I don't agree. Through this kind of video we can raise sensibility and awareness, towards the ideal point tech companies will have to review their behaviour and policies. If nobody (consumers, citizens, governments, world organizations, ..) force them, they will keep doing what's the best for them, obviously. But this doesn't fit with the best for us.

**Comment by micheleminno** [comment]
Imagine this scenario:
I want to search for a medicine effects, but wait: what if this information goes public? It's better not doing it. This will be a nightmare.

**Comment by georgeshk** [comment]
That is a great example. So, you'd rather trust Google with your enquiries about your medicine (which they will remember and add to your profile that you probably have some embarassing medical condition), rather than discuss with your doctor/pharmacist, who are legally held responsible to keep your discussions strictly confidential?

You just demonstrated how the convenience of searching online is worth much more than the guarantee of confidentiality.

**Comment by micheleminno** [comment]
I want to have the possibility and the freedom to search the web for whatever embarrassing personal reason, without the fear of being classified and 'profilated' by anyone.

**Comment by micheleminno** [comment]
In the specific scenario:
there are a thousand reasons to search for medical info, given also that I went to the doctor: 
- experiences of other patiens
- chemical info about the medicine-
- comparison of generics and brand medicines
- ...

**Comment by micheleminno** [comment]
This is what I mea when I say that we need a top-bottom guide, a CHT brand that clarify what's the message we want to give with these campaigns. we here a trying to build the brand (even if you are not enjoying this). There will be many other choices to do like this. These are political (in its bigger meaning of regulating social aspects if people) messages, even if we want to stay as agnostic as we can.

**Comment by georgeshk** [comment]
@micheleminno

Fully agree with your post on the forum about the brand.

What I don't enjoy is having protracted debates, when obviously we will not be able to reach a consensus, on each other's project. I always take all suggestions very seriously, but that doesn't mean I have to accept every one of those, and I will definitely not submit myself to a "vote". We need to respect each other's vision.

Please note I made numerous suggestions on your own project, and you rejected most of them. I did not take it the wrong way or try to debate endlessly. I respected your decision always and told you I would support your vision. I expect the same in return.

Sorry for being a bit blunt here.

**Comment by micheleminno** [comment]
You made suggestion about the content of the video, not about the message. I'm not trying to impose my view, I'm just clarifying better the difference of alternative messages we can give. I think it's something we have to deal with if we want to grow as a community. And apart our one-to-one discussion, no one else seem to care or partecipate, which is the real problem. 
After that, feel free to go on this your vision, but I don't agree with the message of the video, that's all. It's not a big issue.

**Comment by georgeshk** [comment]
No worries, let me try to rewrite the second part so that I could place equal emphasis on both aspects, i.e. changing tech companies' practices and staying safe in the meantime.

**Comment by micheleminno** [comment]
I advance a proposal, not only for this video, but for all videos of 'reality shock' campaign:
What if we don't give any message at the end? I mean, with written words.
After all, it must be a reality shock.ì, the viewer is pushed by empathy to experience the situation we show in the video and that's all. He/she must think of some conclusion/message by him/herself.

**Comment by georgeshk** [comment]
I am entirely against this proposal. The comments are the end highlight the video is not a mere fiction but also provide some background information for further thoughts, leading to mentioning the CHT.

And I don't like the idea of imposing rules that would apply to all videos in this campaign (I imagine this is another aspect of your suggestion to validate the CHT brand). Your video project doesn't include comments at the end. That's fine with me. A bit drastic to require that all other projects should not have any comment, and I would not, conversely, require you to add any comment in yours.

Not up for debate as far as I am concerned.

**Comment by georgeshk** [comment]
Ok, you know what? I am out of here. Was great, but I don't enjoy spending hours of hard, thoughtful work, being destroyed in a matter of seconds with some new revolutionary idea.

Michele, I trust you think very highly of yourself, and probably think I am some stupid guy sitting somewhere with no clue or an ounce of judgement.

After debating about the comments issue, I gave up and decided to redraft. Then you said, "actually, my video doesn't have comments, why would this idiot's projects have comments?"

Yes, it is your project now. Thanks for not crediting me with hours and hours of hard work. I am sure you will do just fine.

**Comment by micheleminno** [comment]
If you think like that, free of quitting, don't blame me. If a debating about what messages conveying to people or how to better shape our videos brings you to such conclusion, it's ok, but I don't have nothing to do with your choice.

**Comment by aschrijver** [comment]
_Please_, I think you two have a basic misunderstanding. The thing that occurs when communicating in online comments only. Happens a lot of times in email correspondence too. Let's discuss this in a PM on the forum.

**Comment by aschrijver** [comment]
This deliverable has been added to the Community Hub. Its location can be found here:

- https://humanetech.community/awareness-program/deliverables/dirty-laundry/
