### ISSUE TITLE
Tech Wise - Promoting prudent technology use in child education”

### ISSUE THREAD

**Issue by healthyswimmer** [humanetech-community/awareness-program#41]
# "Tech Wise" Campaign Theme

## Info 

- Name: Appropriate use of technology in schools
- General discussion: [Forum topic title here](forum-topic-url)

## Summary 

Promoting prudent technology use in child education.

## Topics

- Displacement of developmental motor skills like handwriting.  
- Learning issues with “dictation note taking” on laptops.  Studies show consolidating thoughts and handwriting notes makes better test scores.  
- Screens poses a distraction to learning content.  

## Objectives

- Inform educators of risks of developmental delay and missed milestones when technology replaces certain skills.  

- Form informational campaigns to broadcast the harms children have already experienced related to overuse or inappropriate technology use in schools.  

- Form research groups within school districts measuring motor skills like handwriting and hours spent on laptops vs tablets vs no tech.  (Washington DC has high tech and no tech schools).

- Form a foundation to support case study review/data collection & research in spine health (neuro, orthopedic and pediatric doctors).  A child teen ergonomic advocacy group- to avoid harms in neuromuscular development.  

- Form a multidisciplinary group of physicians (multiple specific specialties), psychologists, physical and occupational therapists, and developmental specialists to collectively come up with guidelines and restrictions on screen use based on real harms seen and theoretical predictions of harm.  

## Description

While some people are successful at limiting screentime for kids, they are inevitably exposed to technology at school.  Educators have good intentions using technology to teach subjects and even making technology THE subject to learn.  Unfortunately, educators are not given the information needed to preserve education while using technology.  Depending on the use, technology is  in schools is replacing some basic skills like handwriting and social emotional peer contact with tools like google classroom.  

Tablet apps to learn math and spelling are distracting with screenbased awards which change the screen multiple times causing dopamine surges to crave more rewards.  

Schools are placed in a difficult position to provide an ergonomically safe tech setup with no funding for this.... the result unfortunately is ill positioning of rapidly growing bodies.  This leads to neuromuscular and postural issues.  Some kids are at more risk than others, so often it appears as if everything is ok.  There are no protections against harms and no awareness either.  

## Strategy

- This theme does not require a high-level strategy. Strategies can be found on individual campaigns.

## Campaigns

- [Campaign 1](campaign1-url) - Campaign 1 short description
- [Campaign 2](campaign2-url) - Campaign 2 short description

## Resources

- This theme has no additional resources yet. Please edit or comment to add your relevant links.

**Comment by aschrijver** [comment]
Great. With help of @patmatsu the info of #37 can be merged in this theme :+1:

**Comment by aschrijver** [comment]
Great start, @healthyswimmer ! Note: In the objectives you can best be short (1-2 lines), then elaborate in the description (particularly applies to 5th objective). Same with topics, i.e. could be:

- Motor skills, handwriting
- Learning issues
- Distractions, concentration

And describe shortly in Description section.

(PS I corrected a comment ending you accidentally deleted, and made Topics header disappear)

**Comment by aschrijver** [comment]
I was wondering if 'Tech Wise' (as a theme) should have campaigns both directed to the professional audience you lay out here - which I find really cool - as well as having campaigns where children are the audience, or both.

In that case detailing the audience is left to the Campaign level an a case-by-case basis. What do you think?

**Comment by healthyswimmer** [comment]
“Also, I wonder if the objectives listed above are methodologies, i.e., means to an end”

End of what?  

Listed objectives are intended to educate the public about harms in Edtech.  We need to educate schools about harms- and make sure federal dollars are not being used to inadvertently harm kids development.  

This is a civil rights issue for kids to develop freely without risk to their health- emotional, developmental and physical.

**Comment by aschrijver** [comment]
Hi @healthyswimmer 

I feel that this Theme should be defined more broadly and generic, so that it can fit many different campaigns in the Kids + Education realm, both targeted at professionals and the broader public.

I suggest that the things you have documented, are moved to a Campaign (issue with Campaign template) instead. And then @patmatsu can define another Campaign for raising awareness to a broader public (non-professionals/experts, like parents and the kids themselves etc.)

**Comment by aschrijver** [comment]
The theme proposal has been transfered to the Community Hub. It now exists at this location:

https://humanetech.community/awareness-program/campaign-themes/tech-wise/
