### ISSUE TITLE
Don't count on me

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/awareness-program#60]
# "Don't Count On Me" Campaign

## Info 

- Name: **Don't count on me**
- Theme: [Resocialized media](https://github.com/humanetech-community/humanetech-community-awareness/issues/61)
- Status: Ideation
- Affiliation: Unofficial
- Original idea: [micheleminno](https://community.humanetech.com/u/micheleminno/summary)
- Coordinator: TBD
- General discussion: [Let’s force social apps to remove numbers from profiles](https://community.humanetech.com/t/let-s-force-social-apps-to-remove-numbers-from-profiles/1466)

## Summary 

Raise awareness on the role of metrics (n. of followers/friends/likes/ ..)  in social media, and take action to have them removed.

## Goals

- Raise awareness with the public how metrics in social media are unnecessary and only serve to increase their dependency on them.

- Force social media companies to acknowledge that users are against counters in social media profiles and feeds.

- Organize frivolous actions for social media users to participate in, to send clear signals to the platform operators and apply public pressure to change.

## Audience

- All people that use social media as they are now or would use them if they were more human and metrics-free.

## Success criteria

- Design actions that are continuated by social media users without the need for community attention
- Other success criteria should be defined based on the deliverables we create.

## Retrospective

- No retrospective has been held yet. The first retrospective is planned at [retrospective date].

## Description

No more n. of followers, n. of likes and so on. It’s a simple but powerful change. it’s the core of the addiction: we see numbers, our brain makes automatic comparisons, we ultimately suffer and strive for more dopamine when the counter increments. In the ideal scenario envisioned by this campaign, social media users would continue to see if someone likes or follows, but no aggregation on users’ actions would be made (how many users did something). That’s where masses of strangers weirdly affect our expectations and our rewards.

### [Deliverable type]: [Deliverable name 1](deliverable1-url) 

[Deliverable summary]

### [Deliverable type]: [Deliverable name 2](deliverable2-url)

[Deliverable summary]

## Strategy

- This is a complex campaign. Besides the (not too long) description, provide a link to a separate [strategy document](campaigns/[campaign-folder]/campaign-strategy.md).

- Additionally you can point to general strategy resources in the `/strategy` folder.

## Funding

- No funding is required to execute this campaign. 

## Resources

- Cognitive and behavioral science pattern that are implemented in social media (see [forum listing](https://community.humanetech.com/t/collecting-cognitive-science-patterns-that-are-at-play-on-social-media/2951))

**Comment by aschrijver** [comment]
## Summary

[replace]

Raise awareness on the role of metrics in social media, and take action to have them removed.

## Goals

[add]

- Raise awareness with the public how metrics in social media are unnecessary and only serve to increase their dependency on them.

- Organize frivolous actions for social media users to participate in, to send clear signals the platform operators and apply public pressure to change.

## Success criteria

- Design actions that are continuated by social media users without the need for community attention
- Other success criteria should be defined based on the deliverables we create.

## Resources

- Cognitive and behavioral science pattern that are implemented in social media (see [forum listing](https://community.humanetech.com/t/collecting-cognitive-science-patterns-that-are-at-play-on-social-media/2951))

**Comment by aschrijver** [comment]
I think one thing we could do is to promote some existing softwares, like the demetricators and newsfeed eradicators on [awesome-humane-tech](https://github.com/engagingspaces/awesome-humane-tech)

Another idea is creating video's of interactions with social media that shows how it look like when all metrics are removed. The 'ideal' view, let's say.

We can start a naming & shaming section on the community website, where we highlight the dark patterns that are at play, and the underlying philosophies of why they are there.

With regards to actions that perpetuate themselves without the need for continued community attention (see goals), I am thinking of other examples, where e.g. Twitter users know how to participate, like by adding the `#darkpatterns` hashtag and thereby notify darkpatterns.org, and similarly you have `#GDPRHallOfShame` to highlight GDPR breaches.

**Comment by aschrijver** [comment]
This campain has been added to the Community Hub. It now exists at this location:

- https://humanetech.community/awareness-program/campaigns/dont-count-on-me/
