### ISSUE TITLE
Eventful Campaign: Foster meetup culture, organize events

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/awareness-program#62]
# "Eventful" Campaign

## Info 

- Name: **Eventful**
- Theme: [Dogfooding](https://github.com/humanetech-community/humanetech-community-awareness/blob/master/themes/dogfooding/README.md)
- Status: Launched
- Affiliation: Official
- Original idea: [@aschrijver](https://community.humanetech.com/u/aschrijver)
- Coordinator: [@aschrijver](https://community.humanetech.com/u/aschrijver)
- General discussion: [This forum topic](https://community.humanetech.com/t/eventful-campaign-foster-a-vibrant-meetup-culture-organize-exciting-events/3024)

## Summary 

Events Program for organizing and promoting community-driven events, and facilitate our meetup chapters.

## Goals

- Foster community culture and member involvement by focusing on face-to-face interactions.

- Provide help and guidelines, to ensure the success of meetup chapters and bootstrap new ones.

- Provide a common home for individual chapters and stimulate information sharing, common activities.

- Promote upcoming events using the community's social media channels.

- Use the Events Program as a means to grow our community with new members.

## Audience

- All existing community members (stimulate event participation)
- Meetup and event organizers (facilitate meetup organizaton and promotion)
- Potential new community members who visit our events (member onboarding)

## Success criteria

- Unifying individual meetup chapters and event activities into one concerted Events Program
- Active reporting, cooperation and cross-pollination between community and community chapters
- Effective promotion of upcoming events, leading to successful, sold-out meetups
- Sufficient volunteers and cooperators to self-sustain the Events Program as an ongoing process

## Retrospective

- No retrospective held yet. Once the Program is under steam, regular retrospectives will be held

## Description

'Eventful' is an ongoing campaign that defines the Events Program of the community.

First goal of the campaign is to merge the efforts of all existing Meetup groups into one unified activity. The HTC has existed as 'only' a forum for the first 9 months after its launch. During this time a total of of [29 initiatives](https://community.humanetech.com/t/eventful-planning-and-organizing-our-meetup-chapters-and-htc-events/3017?u=aschrijver) have started to form meetup chapters all around the world. This has led to:

- 10 active CHT meetup chapters have been erected
- 6 active meetup chapters that are not (directly) affiliated to CHT
- 1 meetup chapter that has been disbanded again
- 12 initiatives to create a meetup group, that have not materialized yet.

Unification starts by rallying current meetup organizers, and providing a common home for meetup chapters on the community website. Parallel to that we'll create a common brand image, and document guidelines and best-practices for meetup / event organization. On the forum there will be spaces to ideate exciting event topics, and coordinate event organization.

### Forum Group: [Event Organizers](https://community.humanetech.com/groups/Events) 

This forum group is for the team of all members involved in event organization and meetup chapter owners. Any member can request to join and in the group we discuss ongoing planning and ideas for the Events Program.

### Community Role: [Event Managers](https://github.com/orgs/humanetech-community/teams/event-managers)

This community role is for active community members that are involved with the Events Program and Eventful campaign for the community as a whole. The role involves continuous improvement of the program and initiating exciting new event initiatives. People in this role can become part of the [Humane Tech Community organization](https://www.linkedin.com/company/humanetech-community) on LinkedIn as 'Event Manager'.

### Community Website: [Meetups Space]() [TODO]

The community website at [humanetech.community](https://humanetech.community) will offer a common space for all meetup chapters (at `humanetech.community/meetups`) and individual chapter homes (at e.g. `amsterdam.humanetech.community`).

Part of the website presence is a common calendar, and individual calendars for each chapter.

## Strategy

The strategy for this campaign is divided into separate parts.

### Facilitating chapters

[TODO]

### Promoting events

All upcoming events will be announced and promoted via all the appropriate community's social media channels:

- Community Meetups site section
- Community forum
- Twitter
- Mastodon
- Facebook
- LinkedIn

Results and feedback on past meetups will be communicated to the above channels as well, and also - where applicable - on:

- Community Blog
- YouTube
- Instagram
- Imgur
- Hacker News

[TODO]

## Funding

- No funding is required to execute this campaign. 

## Milestones

- Inform all community members and event organizers about campaign and Events Program

## Resources

- [Meetups](https://community.humanetech.com/c/community-commons/meetups) forum sub-category under Community Commons
- Campaigners team message: [Investigation of existing meetup chapters](https://community.humanetech.com/t/eventful-planning-and-organizing-our-meetup-chapters-and-htc-events/3017)

**Comment by patmatsu** [comment]
The "Dogfooding" link doesn't work. Also, I don't know if the meetup organizers will agree to being coordinated and reined in. Like ferj, they may revolt against the idea. Just expressing a concern.

**Comment by aschrijver** [comment]
Note: I updated the `Dogfooding` link. It didn't work from `Issues` because it was relative, not absolute, but would work once the text was transferred to its own document. Anyway, it works now.

**Comment by aschrijver** [comment]
This proposal has been accepted and is now part of the Community Hub. It can be found at this location:

- https://humanetech.community/awareness-program/campaigns/eventful
