### ISSUE TITLE
Reality Shock: Video "Caffeine Injection" (formerly "A Coffee Place")

### ISSUE THREAD

**Issue by ghost** [humanetech-community/awareness-program#8]
# "Caffeine Injection" Deliverable

## Info 

- Name: **Caffeine Injection**
- Type: **Video**
- Campaign: [Reality Shock](campaigns/reality-shock/README.md)
- General discussion: [This forum topic](https://community.humanetech.com/t/reality-shock-video-caffeine-injection-campaign-deliverable/3967)

## Summary 

Short video depicting the rapid and drastic growth in smartphone addiction.

## Goals

- Shock the audience into realizing that our world has changed so much and so quickly since the smartphone's advent.

- Contrast previous pastimes and customs with the now universal addiction to our devices.

- Get the audience to ponder whether we should be more than a bit concerned about such drastic changes to our society.

## Concept

Let us look at how our pastimes have changed by considering a scene at a cafe that actually represents two decades. From leisurely and seemingly tranquil activities, we have become increasingly absorbed in our phones, in the process building the wealthiest and most powerful companies in the world’s history. At the end, we realize our phones have become our only source of gratification. 

## Strategy

- This deliverable does not require additional strategy. Please refer to [campaign strategy](campaigns/reality-shock/README.md#strategy).

## Script

The whole scene takes place in one of these coffee place terraces you can see everywhere in Europe. This kind of place used to be cliche for spending time leisurely with friends, reading newspapers or a book, and watching people.

The music starts slowly. Maybe only a few patrons (2 or 3, importantly most of them in their early twenties as this is not a cross-generational issue), all of them engaging in above-mentioned, "traditional" activities.

As the music gathers pace and grows crescendo, more and more patrons of all ages and all backgrounds (students, business people, etc), alone or in groups, sit in, some of them picking up their phones and getting busy. The music grows louder, more and more patrons arrive, this time already holding their phones as they arrive. We start superimposing high-tech transparent windows pertaining to each patron (we start with one window/patron, then add another patron, another, etc) that is relevant for data harvesting, and keeping us ever-entertained.

The superimposed windows show the computer scripts that run at all times, making users very busy indeed, and where you see processes being executed one by one:

- Name, sex
- Income level, user segment (say "high-value", "mid-value", "low-value")
- "New message... parsing..."
- "New interest identified... updating profile... pushing notification... Done"

We can think of other computer scripts (ideas are welcome) (otherwise, if only one process is shown for every one, too boring), for instance:

- Name, sex
- "New friend request..."
- "Connection added..."
- "Updating graph..."
- "Pushing update...Done"

Or:

- Name, sex
- "Uploading new picture..."
- "Analyzing content..."
- "Updating profile... Done"

We would then show one patron who is checking his stock portfolio. He looks at famous - or fictitious - tech stocks charts, showing - as we all know - vertiginous increases in stock prices.

Once the music finally calms down in the very last few seconds (just before 2:37), one person who was engrossed with his/her phone looks up from his/her screen, and realizes there is not a soul around.

At the end of the video, the music turns into the following: [Ominous music turning to drums and pipes](https://www.youtube.com/watch?v=eyqPGiP7xiQ&list=PL8B2594BB7C0FB81A), we switch to a black background, and show successive lines of text (one at a time), as follows:

"In late 2017, Ray Kurzweil, Google's guru of AI and futurism, made the prediction that humans and machines will soon become one."

[Pause]

"Many of the world's most powerful companies are already actively pursuing this vision."

[Pause, new screen]

"If Mr. Kurzweil's prophecy were to prove accurate, there could be very little left of what today makes us truly humans."

[Pause]

"Now may be the last opportunity to fight for humanity as we know it. Learn more about humane technology and join the cause at www.humanetech.com." (This sentence coincides with the moment you hear the first drums in the music)

## Duration

- Short, probably 2:37 mins. (determined by music).

## Music

- First 2:37 mins. of Beethoven’s Symphony 7 Movement 2 (“allegretto”). Listen [here on Youtube](https://www.youtube.com/watch?v=mgHxmAsINDk)

- Scottish drums and pipes (conclusion). [Listen here on Youtube](https://www.youtube.com/watch?v=eyqPGiP7xiQ&list=PL8B2594BB7C0FB81A)

## Production

We would need to find a professional video producer, most likely in Europe. They will have to propose and arrange a shooting venue (the cafe) and secure actors of different age groups.

## Funding

- Funding requirements have yet to be determined. 

## Team

- To be determined

## Resources

- Preferable music to use by Beethoven’s Symphony 7, Movement 2 "Allegretto": [Listen here on Youtube](https://www.youtube.com/watch?v=mgHxmAsINDk)

**Comment by micheleminno** [comment]
I can contribute on the first video script, ideas and maybe storyboard…
according to me, the main concern is how to avoid cliches about these kind of videos where someone tells you to be afraid of something. The video should flow as natural as possible, without underlying the bad points of the whole situation too much. I will think about it.

**Comment by georgeshk** [comment]
> the main concern is how to avoid cliches about these kind of videos where someone tells you to be afraid of something. The video should flow as natural as possible, without underlying the bad points of the whole situation too much.

Agreed. Looking forward to seeing your ideas. Please listen to the music while you try to picture the scene. It is important because this music evokes progress, but also has some nostalgia in it. To address your main concern, I believe the video can be made neutral up to the very last few seconds where the person realizes he is alone. That fits with the campaign theme of "Reality Shock"

**Comment by micheleminno** [comment]
I was thinking that two minutes and a half are a lot. We need a story with a character people can relate to. 
My idea is to show a person 'A' (man or girl) interacting with all other changing people from the beginning (located in time somewhere at 1950-60) to the end (present time or maybe near future).
So for example A at the beginning is playing pool with friends, laughing, smoking, making jokes loudly. Then smoothly the scene changes and A is discussing animately with other people (years '68 or so) with other clothes, other styles and fashion. Then the same for '80, '90, '00 just till the last part when everybody else (including A) is at their smartphones. 
At the end A looks up from the screen directly into the camera for the first time (he/she could be alone or surrounded by silent people down on their phones) and says with a nostalgic face something like: "It was fun when I lost at the pool and they made me go to every woman (or man) in the club asking if they wanted to go out with me..".

**Comment by patmatsu** [comment]
Want to point out that you can purchase stock footage at [Vimeo](https://vimeo.com/stock).

**Comment by georgeshk** [comment]
> My idea is to show a person 'A' (man or girl) interacting with all other changing people from the beginning (located in time somewhere at 1950-60) to the end (present time or maybe near future).
So for example A at the beginning is playing pool with friends, laughing, smoking, making jokes loudly. Then smoothly the scene changes and A is discussing animately with other people (years '68 or so), other clothes, other styles and forniture. Then the same for '80, '90, '00 just till the last part when everybody else (including A) is at their smartphones.

Hi Michele, your idea is quite distinctive and could form the basis of another video (there is no problem having several videos covering the same themes). Please create a new issue and submit your concept using the format above (no need to create a table as I did, just provide details for all required fields in a text format with separate titles for each field).

**Comment by georgeshk** [comment]
> I was thinking that two minutes and a half are a lot.

The proposed video duration is 2:37, matching the music theme. I will watch a couple of videos of the same duration and take note of how much happens/should happen in that timeframe (so as to anticipate the needs of our future storyboard). So far, not so much concerned, as the music theme is very engaging and powerfully building momentum.

**Comment by georgeshk** [comment]
> We need a story with a character viewers can relate to.

Nothing wrong with having a central character viewers can relate to (I was thinking of another story where we follow someone experiencing the aftermath of a data breach), however it is not always necessary. 

In the proposed video here, we depict a crowd scene, there are many characters with whom we can associate. They represent society as a whole going through a dramatic and sudden transformation.

**Comment by georgeshk** [comment]
> Want to point out that you can purchase stock footage at Vimeo.

Hi @patmatsu , Right now the plan is to commission professional video producers. Producing a high-quality video is a complex business, and it is hard to imagine we can form a full production team in-house.

**Comment by micheleminno** [comment]
> your idea is quite distinctive and could form the basis of another video (there is no problem having several videos covering the same themes). Please create a new issue and submit your concept using the format above

Ok, you're right, I will do it.

**Comment by georgeshk** [comment]
Hi @micheleminno

Great to have fresh ideas! Looking forward to reading your detailed script.

**Comment by micheleminno** [comment]
Is there a way viewers can understand the temporal switch between the first customers busy in traditional activities and the new customers busy with their smartphones? Or is it just guided by the crescendo of the music?

**Comment by georgeshk** [comment]
Hi @micheleminno

Good question. My thinking was to make the temporal switch implicit (and you are right, the music makes it so, as it evokes irresistible progress). At first, the new patrons seem like the first, but after a while they pick up their phones. More and more waves of new customers, this time arriving with their phones up, talking or typing.

I picture it would work this way. Making it more explicit and it kind of ruin the aesthetic appeal of the video by making it too obvious.

I believe that our videos should be sometimes kind of mysterious and intriguing, besides last second twists and turns.

**Comment by georgeshk** [comment]
> We start superimposing data (in the form of these high-tech transparent windows) pertaining to each patron that is relevant for harvesting, and showing growing profits, market caps for tech companies, etc. 

The superimposed windows could show the computer scripts of tech firms running at all times, making users very busy indeed, and where you see processes being executed one by one:

- Name, sex
- Income level, user segment (say "high-value", "mid-value", "low-value")
- "New message... parsing..."
- "New interest identified... updating profile... pushing notification... Done"

We can think of other computer scripts (ideas are welcome) for other applications (otherwise, if only one process is shown for every one, too boring), for instance:

- Name, sex
- "New friend request..."
- "Connection added..."
- "Updating graph..."
- "Pushing update to network...Done"

Or:

- Name, sex
- "Uploading new picture..."
- "Analyzing content..."
- "Updating profile... Done"

This is for brainstorming and seriously needs a sanity check. We need to be realistic and honest, not fictitious here, and also we need to be as neutral as possible, so cannot show a really dark/evil side to this.

For the tech companies' revenues/profits side, we could have one of the patrons (say, some guy in suit) checking his stocks, which would show the explosion in each tech company's market capitalizations. I think it is a good compromise as it appears neutral (well, we do have an agenda) - who does not want to see his stock portfolio grow? But at the same time it implies that since we are not paying for anything, we should seriously wonder about where this massive "free lunch" comes from.

Disclaimer: **I am not advocating the downfall of big tech companies here**. They have the power to reinvent themselves with designs that adopt humane tech principles, and thrive.

**Comment by aschrijver** [comment]
Love the idea, @georgeshk We can create a sub-task (issue) and look in our community for someone with UX / animation skills that can design the windows concept further, and assign to her/him.

**Comment by aschrijver** [comment]
I've been thinking this video deliverable should have a different name. Whereas a theme or campaign has a working title, the video deliverable name is part of the campaign strategy. It should help attracting attention to the video, together with the video thumbnail (a clickbait-y snapshot from the video). If I only encounter the video title, I will probably not click-through. If there is a thumbnail, it should be perfect, or I will still skip the video.

If the focus is more on how hectic our society has become, triggered by big tech manipulating us, the title could be something like 'Caffeine Shot'. If it is more about data harvesting, it could be 'Coffee Extraction' (from extract; could also be 'distraction'). Or better titles.

**Comment by georgeshk** [comment]
> I've been thinking this video deliverable should have a different name

Fully agreed. I really like something like "caffeine shot", as it is more neutral, will think about it further.

**Comment by georgeshk** [comment]
Ok, I came up with two proposals for the title:

- "Espresso shot"
- "Caffeine injection" (my preference, better at evoking a benign "drug" we inject ourselves with to stay awake)

@aschrijver, @patmatsu, @micheleminno: your preferred option?

**Comment by micheleminno** [comment]
Maybe it's useful to have a title that reminds also the data extracted from the people activity on their phone:
* "Coffe for data"?

**Comment by micheleminno** [comment]
“Smartphone is the new cigarette”?

**Comment by georgeshk** [comment]
> “Smartphone is the new cigarette”?

Mmm... Only a minority of people smokes, while the vast majority of the population uses smartphones. Most of us drink coffee. We also know coffee is a benign "fix", while cigarettes kill (smartphone users wont accept being likened to smokers, whom most of them condemn).

**Comment by georgeshk** [comment]
We could also add a line after the reference to Mr. Kurzweil, as follows:

"Many of the world's most powerful companies are already actively pursuing this agenda."

**Comment by georgeshk** [comment]
More and more I believe the title of the video should be "Mankind 2.0" (same as the theme). It powerfully expresses what this is about and makes reference to humanity as a mere piece of software that allegedly needs an update.

**Comment by georgeshk** [comment]
"And he causeth all, both small and great, rich and poor, free and bond, to receive a mark in their right hand, or in their foreheads:

And that no man might buy or sell, save he that had the mark, or the name of the beast, or the number of his name."

Revelations 13:16-17

It is not unusual for post movie text to show quotations from religious texts.

**Comment by micheleminno** [comment]
> "In late 2017, Ray Kurzweil, Google's guru of AI and futurism, predicted humans and machines will eventually merge."

>"If his prophecy were to prove accurate, it is quite possible there will be very little left of what makes us humans today."

>"Now may be the last opportunity to fight for humanity as we know it. Learn more and join our cause at www.humanetech.com."

>Music could be Rage Against The Machine's "Wake up".

Is it no too Matrix-oriented?

**Comment by micheleminno** [comment]
> "And he causeth all, both small and great, rich and poor, free and bond, to receive a mark in their right hand, or in their foreheads:

>And that no man might buy or sell, save he that had the mark, or the name of the beast, or the number of his name."

>Revelations 13:16-17

>It is not unusual for post movie text to show quotations from religious texts.

Citations from one religion may push away viewers of other religions..

**Comment by micheleminno** [comment]
> There is nothing too Matrix-inspired in the proposed text. It doesnt say "There will be very few humans left", but "Little may be left of what makes us truly human". 

In Matrix there are a lot of humans, but they don't have what makes us truly human because they are merged with the machines, serving as energy source for them and their software. Only a few humans, those ones living in Zion, can be considered truly human.

**Comment by georgeshk** [comment]
> In Matrix there are a lot of humans, but they don't have what makes us truly human because they are merged with the machines, serving as energy source for them and their software. Only a few humans, those ones living in Zion, can be considered truly human.

Ok. Still, we are not suggesting here that we are concerned we will be turned into energy source for machines. We don't know exactly what "Mankind 2.0" will look like. But our concern is that in the process of turning into man-machines, we will have to shed much of our true humanity.

Anyway, even if parallels can be drawn to Matrix, it was a good movie. The video we produce does not offer an apocalyptic vision of us turning into energy sources, but shows that there is a rapid evolution in what is regarded as "normal" human behavior. We are on a slippery slope, and fear of the unknown is a great motivator.

**Comment by micheleminno** [comment]
> While I do not fully agree, I am perfectly fine using only the text above without the reference to Revelations.

Yes, you are right, people from other religions may feel anyway the religiosity of a text from another religion. But it could push away people with no religion at all. 
Do as you feel, include it if in your idea it fits with the rest of the message..

**Comment by georgeshk** [comment]
Hi @aschrijver @micheleminno , I updated the script in the top post here. It is now very detailed and quite mature.

I would like to ask for a little bit of help from all of you who are based in Europe (given the concept of the video here). Not much. If you could just do a little bit of research and identify, maybe 5 promising "film production companies" (that is the term I found is the best way to find what we are looking for on Google).

For instance, "film production companies Hong Kong" gave me several links to lists of local professional film production companies. See for instance this link https://www.kftv.com/city/hong-kong/country/hong-kong. That is what we are looking for.

Select 5 production companies that seem highly professional, present well, but not "over the top". No need to approach them now (we need more discussions first).

I know, I know, it is work and not so glamorous, but would really appreciate your kind assistance.

**Comment by micheleminno** [comment]
I don't like last part of the video, with sentences about guru's citations. I'd prefer some sentence about collected data, income for tech companies coming from the users data and so on. Some real glimpse about what it's the situation today. In that case also the 2nd music would be another one, better if no music at all.

**Comment by georgeshk** [comment]
>  In that case also the 2nd music would be another one, better if no music at all.

Disagree with this. Purposeful to have inspiring music in the post-video comments. And the proposed music theme is just fantastic and fit to promote cause worth fighting for.

**Comment by georgeshk** [comment]
> I don't like last part of the video, with sentences about guru's citations. 

It is most powerful to quote prominent executives on where they see the future. This makes people take things into serious consideration. Just listing out general views on such topics is much less powerful.

**Comment by micheleminno** [comment]
I don't know, what the guru says doesn't convince me, it doesn't seem very related to people on their phones giving away sociality, attention and their data to business companies. 
But as always the final choice is yours.

**Comment by Dori-CHT** [comment]
Very nice! The Coffee Place is a great idea. Regarding other computer scripts (for the superimposed window):  A couple is sitting at separate tables unaware of each other. They're  looking at the same dating app which connects them based on common interests/activities (hiking, skiing, etc. ). One gets up to leave and sees their partner engrossed in the app (or they both look up at the same time). Time to "deep six" the smartphones - **electronic recyle bin** in coffee shop?  Leave together  - only if they each agree to eliminate the phone? Maybe this is another script?  Different music comes to mind: "Escape"  the Pina Colada song. So many ways to go with this one....
***Electronic Recyle Bin*** (**phone zombie image on bin superimposed with skull & crossbones)**
*Name, sex
*Activities...
*It's a match!  You have 3 places in common!

Does the 1st example you gave already refer to this scenario?

**Name, sex
Income level, user segment (say "high-value", "mid-value", "low-value")
"New message... parsing..."
"New interest identified... updating profile... pushing notification... Done"**

**Comment by georgeshk** [comment]
@Dori-CHT 

Thanks for the suggestion. It is an interesting idea, my issue with it is that it does not really fit with the whole script here. Dating apps help bring people together, here the scripts should give a more somber vibe, i.e. computer programs taking over our private lives and precious time. We also want to highlight the fact that computer programs are in effect seeking to entrench a deep human-machine relationship (which is why, at the end, one person looks up and realizes everybody is gone, and he is left alone with his phone).

> Maybe this is another script? Different music comes to mind: "Escape" the Pina Colada song. So many ways to go with this one....

Yeah I guess that would be a different video concept.

**Comment by georgesnew** [comment]
Once we have the RFP finalized, I will start approaching [movie production companies](https://github.com/humanetech-community/humanetech-community-awareness/issues/51) to get quotes and proposals. This will give us a good idea.

**Comment by aschrijver** [comment]
On that last point: We should be able to act on that as a community, which we cannot yet. Or this should be an 'unofficial' campaign deliverable (let's discuss on the forum, when the time is there).

**Comment by aschrijver** [comment]
This deliverable has been added to the Community Hub. Its location can be found here:

- https://humanetech.community/awareness-program/deliverables/caffeine-injection/
